### ISSUE TITLE
./menzies/CorrelationVsCausation.md

### ISSUE THREAD

**Issue by timm** [ds4se/chapters#38]
After review, relabel to 'reviewTwo'. After second review, relabel to 'EditorsComment'.

**Comment by taoxiease** [comment]
# Review template

## Title of chapter

Correlation is not Causation (or, when not to scream "Eureka!")

## URL to the chapter

https://github.com/ds4se/chapters/blob/master/menzies/CorrelationVsCausation.md

## Message?

Correlation is not causation.

## Accessible?

Yes

## Size?

In the last paragraph, the author suggests the following "And while you wait, critically and carefully review how you reached that result. See if you can reproduce it using other tools and techniques or, at the very least, implement your analysis a second time using the same tools (just to check if the first result came from some one letter typo in your scripts)."

However, such suggestion doesn't seem to address those issues faced in the example case studies in the section of "Case Studies in SE", e.g., in Kocaguneli et al.'s work. The author is suggested to relate the suggestion back to these example case studies and see whether following the suggestion can avoid or alleviate the pitfalls identified in these example SE case studies.

## Gotta Mantra?

The title looks good.

## Best Points

SE case studies and what to do in such context.

**Comment by turhanb** [comment]
## Title of chapter

Correlation is not Causation (or, when not to scream "Eureka!")

## URL to the chapter

https://github.com/ds4se/chapters/blob/master/menzies/CorrelationVsCausation.md

## Message?

Correlation is not causation

## Accessible?

Vic Basili and Steve Easterbrook's high profiles in SE can be emphasised to make the generic audience realise why you cite examples/ methods from them.

Considering the general target audience, it would be good to explicitly say SE stands for Software Engineering in the subheading "Case Studies in SE" :) Maybe you can also consider "Examples from SE" rather than 'case studies'

## Size?

Is the Example figure 12x25? To be consistent with the 300 throw discussion I guess it should be, but it's very difficult to count the columns, a brief description would help when introducing it.

Conversion to percentages lose precision, you can consider using '1/4, 1/8, 1/16, 1/32'; or note the rounding factor when converting to percentages. Also, these do not depend on whether we throw 300 times or not, so you may consider rewording without using "if 300 throws, then probabilities are..." struct.
.
A few typos to fix:
Section: What not to do: "And least, don't do it straight away." --> "At least ..."
Section: Example: "where, in fact, no such pattern exits" --> "... exists"
Section: Example: "too many runs long runs of" --> "too many long runs of"
Section: Case Studies in SE "seemed to produced " --> "seemed to (have) produce(d)"
Section: What to Do: " by researchers were pursuing other goals:" --> drop "were"

## Gotta Mantra?

Current title is ok.

## Best Points

The flow is really nice. The chapter concisely delivers a message and recommendations based on relevant examples.

**Comment by tzimmermsr** [comment]
@timm Please prepare a new version of your paper by January 13 taking the reviewers' feedback into account.

**Comment by tzimmermsr** [comment]
@timm Any updates on the revision?

**Comment by timm** [comment]
@tzimmermsr Changed and committed. Typos fixed. 

@taoxiease's comment was spot-on; so jiggled the conclusion some to better address his point. 

@turhanb  made some good comments too and i used them all

**Comment by tzimmermsr** [comment]
Thanks @timm . All good.
