### ISSUE TITLE
./hongyu/SuccessStory.md

### ISSUE THREAD

**Issue by timm** [ds4se/chapters#45]
After review, relabel to 'reviewTwo'. After second review, relabel to 'EditorsComment'.

**Comment by jaccz** [comment]
A great chapter. I read it with interest. 
- It would be great to illustrate the incident management workflow with a graphic.
- Change "The technical details can be found elsewhere [4, 5]." to The technical details can be found in [4, 5].
- There are double spaces at the end of some sentences. Change to consistently use single space.
- "Security token rebuilt" is capitalized in one place. Change to lower case.
- Nit-pick: swap second and third bullet so that mining historical patterns appears before mining new patterns. Seems logically progressing from less complex to more complex. 
- Consider adding a representative screenshot from the tool.
- Can you mention the name of the Microsoft Service on which SAS was used. If not, can we not say "X"? "One of Microsoft large services" sounds better than a cryptic letter (unless "X" is an actual project name :)).
  "During a certain period of time" -> "In the past".

**Comment by CaptainEmerson** [comment]
## Message?

Doing data analytics for services is hard, and here are some tools for doing it.

## Accessible?

The chapter uses good terminology, with good references for more reading. One way it might be made more accessible is to remove the acronyms. For instance, OCEs might first be introduced as "on-call engineers, or just 'engineers' for short in this chapter."

## Size?

The chapter is the right length.

## Gotta Mantra?

The title isn't particularly catchy. Something ideas:
- How to Train Your Data Services (http://www.imdb.com/title/tt0892769/)
- More Reliable Services, Faster

## Best Points

The best point of the chapter is that it's got a practical tool that goes with it, which has been shown to be effective in a case study.

## Other suggestions
- [ ] The biggest suggestion I could make is, what is the reader supposed to get out of this if they don't use your tool? Are there some best practices that you've learned?
- [ ] I've put a bunch of minor changes in pull request https://github.com/ds4se/chapters/pull/107
- [ ] "in most cases," Evidence? There are a few other places with "most" or "usually" -- I also wonder whether some evidence is appropriate here.

**Comment by CaptainEmerson** [comment]
@timm , I don't have permission to change labels. Please go ahead and change to EditorsComment.

**Comment by timm** [comment]
@hongyujohn thanks for your revisions.

Chapter text is good. The title is still... not so fantastically exciting. Recall that there will be 60 to 70 chapters in this book. Your title needs to STAND OUT, least it disappears into the crowd. Any of Emerson's titles any good for you? Or something else?

**Comment by hongyujohn** [comment]
ok. I have revised the paper title according to the reviewers' suggestion: 
How to Tame Your Online Services

thanks.

**Comment by timm** [comment]
@hongyujohn :+1:  good to go.
