### ISSUE TITLE
./oivo/bringData.md

### ISSUE THREAD

**Issue by timm** [ds4se/chapters#66]
After review, relabel to 'reviewTwo'. After second review, relabel to 'EditorsComment'.

**Comment by obaysal** [comment]
# Review template

## Title of chapter

In god we trust, all others bring data – BIG DATA!

## URL to the chapter

https://github.com/ds4se/chapters/blob/master/oivo/bringData.md

## Message?

What is the chapter's  clear and approachable take away message?

Data science is able to replace traditional assessments of software process improvement. 

## Accessible?

Is the chapters written for a generalist audience (no excessive use of technical terminology) with a minimum of diagrams and references?
How can it be made more accessible to generalist?

If the audience is limited to practitioners, then the message is the right one; no need to convince researchers how powerful the data and analytics can be. 

## Size?

Is the chapter the right length?
Should anything missing be added?
Can anything superfluous be removed (e.g. by deleting some section that does not work so well or  by using less jargon, less formulae, lees diagrams, less references).?
What are the aspects of the chapter that authors  SHOULD  change?
- The chapter is of the right length. However, the background (history) about SPI and traditional assessment methods can be shorten up a bit. 
- Personally, I don't think the 'why it is happening' question is any less important than the 'what is happening' one. I think data science is capable of addressing both. 
- I'd use 'data science' instead of the plural form used here ('data sciences'); minor typos: 'data science has also been used in' and 'data science has not yet reached'.

## Gotta Mantra?

We encouraged (but did not require) the chapter title to be a mantra or something cute/catchy, i.e., some slogan reflecting best practice for data science for SE?  If you have suggestion for a better title, please put them here.

While the title is catchy, I feel it's a wrong choice for the chapter. I thought the message was about leveraging data science not collecting big data, big data is meaningless without appropriate data science.

## Best Points

What are the best points of the chapter that the authors should NOT change?

The key message of the chapter is a good one - data analytics is a powerful thing! Also the examples of the type of analytics (e.g., predictive analytics) that can be more useful than traditional assessment methods in offering insights and supporting actions and decisions related to process improvements.

**Comment by Zhitao** [comment]
# Review template

## Title of chapter

In god we trust, all others bring data – BIG DATA!

## URL to the chapter

https://github.com/ds4se/chapters/blob/master/oivo/bringData.md

## Message?

What is the chapter's  clear and approachable take away message?

Traditional SPI can be improved by using data science and data analytics.

## Accessible?

Is the chapters written for a generalist audience (no excessive use of technical terminology) with a minimum of diagrams and references?
How can it be made more accessible to generalist?

Yes. It's quite accessible.

## Size?

Is the chapter the right length?
Should anything missing be added?
Can anything superfluous be removed (e.g. by deleting some section that does not work so well or  by using less jargon, less formulae, lees diagrams, less references).?
What are the aspects of the chapter that authors  SHOULD  change?

The chapter length is ok.

## Gotta Mantra?

We encouraged (but did not require) the chapter title to be a mantra or something cute/catchy, i.e., some slogan reflecting best practice for data science for SE?  If you have suggestion for a better title, please put them here.

The title is catchy.

## Best Points

What are the best points of the chapter that the authors should NOT change?

I like the way author introduce the challenges in traditional SPI and suggest how we can improve it using data science.

**Comment by tzimmermsr** [comment]
A few smaller changes (in addition to the above reviews)

data sciences => data science

Define acronyms consistently:
PDCA (Plan-Do-Check-Act) => Plan-Do-Check-Act (PDCA) 
CMM (Capability Maturity Model) => Capability Maturity Model (CMM) 
CMMI (Capability Maturity Model Integration) => Capability Maturity Model Integration (CMMI)

US Department of Defense (DoD) has => US Department of Defense has 
[no need to define DoD, since it is not use in the remainder of the chapter]

**Comment by tzimmermsr** [comment]
@maoivo Please prepare a new version of your paper by January 13 taking the reviewers' feedback into account. 

I agree that the title --- while catchy --- is not a good choice for the chapter. The chapter will have more impact if it relates Software Process Improvement in some way to data science.

You can still keep the quote, simply start the Introduction with the sentence as a quote: "In god we trust, all others bring data." The legendary statement of the quality guru W. Edwards Deming has been used...

If you want to keep the quote with BIG data, you could add it as a heading after the first paragraph.

**Comment by maoivo** [comment]
- Changed the title
- Clarified the need for data science.
- Shortened intro to SPI 
- Overall editing of language and clarity of the text throughout the chapter.

**Comment by tzimmermsr** [comment]
Thanks @maoivo for making the changes. It's good to go from my side.
