### ISSUE TITLE
./siravegas/Challenges SE Experiments.md

### ISSUE THREAD

**Issue by timm** [ds4se/chapters#75]
After review, relabel to 'reviewTwo'. After second review, relabel to 'EditorsComment'.

**Comment by maoivo** [comment]
## Title of chapter

Challenges of Conducting Software Engineering Experiments: How to Stop Things Going Wrong

## URL to the chapter

https://github.com/ds4se/chapters/blob/master/siravegas/Challenges%20SE%20Experiments.md

## Message?

SW engineering experiments are useful but we need carefully planned discipline specific practices (tools) to run them.

## Accessible?

The chapter is accessible to audience that has some background knowledge in empirical software engineering. The amount of technical terminology could be slightly less for generalist audience.

## Size?

Is the chapter the right length? Yes
Should anything missing be added? No
Can anything superfluous be removed (e.g. by deleting some section that does not work so well or  by using less jargon, less formulae, lees diagrams, less references).? No
What are the aspects of the chapter that authors  SHOULD  change?

The text in general is fine. Fluent and easy to read. Giving it some catchy flavor for generalist audience could improve the attractiveness.

## Gotta Mantra?

The title is professional rather than catchy for generalist audience.

## Best Points

Compact collection of excellent advice for running experiments in SW engineering.

**Comment by tzimmermsr** [comment]
Review by @GRuhe (moved from #111):

## URL to the chapter

_the markdown file. e.g. https://github.com/ds4se/chapters/blob/master/siravegas/Challenges SE Experiments.md_

## Message?

What is the chapter's  clear and approachable take away message?

_”One size does not fit all” applies to SE experiments as well_

## Accessible?

Is the chapters written for a generalist audience (no excessive use of technical terminology) with a minimum of diagrams and references?
How can it be made more accessible to generalist?

_Yes, it is written in a non-technical language, easy to understand also for non-experts_

## Size?

Is the chapter the right length?
Should anything missing be added?
Can anything superfluous be removed (e.g. by deleting some section that does not work so well or  by using less jargon, less formulae, lees diagrams, less references).?
What are the aspects of the chapter that authors SHOULD  change?

_Length is right, language easy to understand.
-   For the definition of experiments, would replace “observe” (software development by “analyze”. 
-   Saying “measurement procedure in SE very often is non-standard” … does this mean the metrics are context specific, but the procedure IS (kind of) standard (GQM)?
-   Would be nice to outline potential implications of NOT following the stated guidelines. were used at AT&T._

## Gotta Mantra?

We encouraged (but did not require) the chapter title to be a mantra or something cute/catchy, i.e., some slogan reflecting best practice for data science for SE?  If you have suggestion for a better title, please put them here.

_What can go wrong in SE experiments?_

## Best Points

What are the best points of the chapter that the authors should NOT change?

_Making clear that not all experiments automatically are meaningful and pay off_

**Comment by tzimmermsr** [comment]
@siravegas @nataliajuristo Please prepare a new version of your paper by January 13 taking the reviewers' feedback into account. In particular, focus on making the text more accessible for generalist audience who is less familiar with experiments and terms such as controlled experiments, one-factor between-subjects experiments, etc. This will increase the impact of your chapter.

**Comment by timm** [comment]
@tzimmermsr 

what do i tell publisher? good to go?

**Comment by tzimmermsr** [comment]
@timm This is good to go. I've updated status + title in the Perspective Book Status.

Thanks @siravegas @nataliajuristo for the revision.
