### ISSUE TITLE
./stephan_diehl/visualization.md

### ISSUE THREAD

**Issue by timm** [ds4se/chapters#78]
After review, relabel to 'reviewTwo'. After second review, relabel to 'EditorsComment'.

**Comment by barik** [comment]
## Title of chapter

Visualizing data is important, or Visualize often and double check

## URL to the chapter

https://github.com/ds4se/chapters/blob/master/stephan_diehl/visualization.md

## Message?

Visualizing data is an integral part of the research process, and can be used in many different stages of the research process. 

## Accessible?

The chapter has some jargon (though it's probably obvious for people in information visualization!), and I would try to add short layman descriptions for some of these terms as they are introduced. For example:
- The sentence, "For example, you could apply sequence rule mining" might be changed to "For example, you could apply sequence rule mining, a technique used to detect patterns in data where values are delivered in a specific order." Same with terms like "node-link diagram".
- For "parallel coordinates" and "decision tree", I think it would be nice to have two figures corresponding to these. For a paper on visualization, I think it makes sense for the reader to actually see some visualizations. Although this contradicts the general advice of minimizing diagrams, in this case I think an exception is warranted.

The section "Some examples?" also seems to pivot around a single story. Perhaps this section should instead be named something like "Leveraging Visualizations: An Example with Software Repository Histories". Then, have a brief sentence on what a version control history is, followed by the problem: "Data extracted from software repositories may have been corrupted [...]." Although, I'm not sure corrupted is the right word. Maybe "problematic" instead?

Near the end of the article, there is the wording, "If you are not sure, ask a visualization expert." Presumably, if they had an expert handy, they wouldn't need the book! So perhaps give a more concrete set of pointers here. One example might be: "If you are not sure, check literature on information visualization, exploratory data analysis, or the infoviz mailing lists at [...]." I know for me, one of the difficult things in getting started is having the right keywords. 

I would end the article on a positive note. Right now it ends with a criticism, which is fine, but the very last sentence of sentences I think should somehow how the reader benefits from the article. Perhaps tie-back to the original theme of how visualization is powerful and should be integral in the analysis process.

Finally, a minor nitpick, but "e.g." and "i.e." get used a lot in the article. To make the language flow more easily, maybe use phrasing like "that is", or "for example" explicitly to add variety.

## Size?

The chapter length is adequate. I think the section currently called "Some examples?" could use some paragraph breaks. Currently it is a bit intimidating as it is one long paragraph.

The story gets a bit muddled when it introduces "interaction." That was not something I was expecting. So if interaction is important, perhaps it can be intertwined in the example throughout. Otherwise, this might be superfluous and beyond the scope of this sort article.  

## Gotta Mantra?

When I read the introduction, I was thinking that the mantra is something like "Visualizing end-to-end" or "Visualizing throughout the research process" or something like that. I think novices (myself included) tend to think of visualization as the final publication end-product. But this article makes it clear that visualization is not just camera-copy; it's something that should be done often as part of the analysis process itself to gain insight. The title should somehow reflect that, and maybe that can be the story of the article as a whole.

## Best Points

The use of terms like sequence rule mining, parallel coordinates, decision trees, and so on make it clear that there is a lot of richness in visualization above and beyond, say, "bar graphs." I think it's important to keep this, but I would make these terms more accessible by adding a simple explanation for each as you introduce the term.

**Comment by barik** [comment]
The other review appears to have been made a separate issue, rather than a comment: Issue #98.

**Comment by tzimmermsr** [comment]
I consolidated the reviews into a single issue report (#98 because everyone was subscribed to it.)
