### ISSUE TITLE
./tomFr/measuringProd.md

### ISSUE THREAD

**Issue by timm** [ds4se/chapters#79]
After review, relabel to 'reviewTwo'. After second review, relabel to 'EditorsComment'.

**Comment by rvprasad** [comment]
## Title of chapter

Measuring individual productivity

## URL to the chapter

https://github.com/ds4se/chapters/blob/master/tomFr/measuringProd.md

## Message?

There is no easy way to measure individual productivity; even in software.

## Accessible?

Yes, the content is accessible to general audience.

## Size?

It is just about the right length.

All sections end with sentences that reinforce the section title.  However, section _Measure the process, not the outcome_ ends with two sentences about how to improve process measurement.  Since a symmetric structure might help the flow, how about moving the last two sentences as a footnote and ending the section with a title reinforcing sentence?

Since the last section is about specific recommendations of what to consider in future research of individual productivity, it might help to list of recommendations.  For example, 1) consider the situation and context, 2) consider other aspects, 3) effect of measurement, and 4) privacy.

## Gotta Mantra?

How about _Measuring Individual Productivity is Hard_?

## Best Points

Unlike other chapters that are horizontal and cut across different aspects of software, this chapter is vertical and focuses on individual productivity.  Keep this distinguishing aspect.

**Comment by pruneson46** [comment]
## Title of chapter

Measuring individual productivity

## URL to the chapter

https://github.com/ds4se/chapters/blob/master/tomFr/measuringProd.md

## Message?

Be careful how you design your productivity measures.

## Accessible?

The chapter is accessible for a generalist. Thanks to the extensive use of examples from other domains (fitness and health) the text connects to everyday experiences.

## Size?

The chapter is of right length. However, since I propose extensions below, that has to be compensated by reducing som parts. The fitness examples may be given with somewhat less detail. I think they are quite well known and understood, so the need less detailed explanation.

I would like to have the integrity aspects extended -- now it is only mentioned as a last comment. Not only that integrity is an issue of its own, it also may have an impact on the measurements. Again with the fitness analogy: if my health insurance company got access to my data, and possibly set my insurance rate after them, I would probably make sure they fit the purpose rather than the reality. 

Another issue that may be worth mentioning is the relation between multiple individual's productivity, i.e. the team or project level. It could benefit the team if one individual does something that lowers his/her individual productivity. The message is: don't sub optimize on the individual.

## Gotta Mantra?

Measuring individual productivity -- you'll get what you measure

## Best Points

Example based approach.

**Comment by tzimmermsr** [comment]
@tomFr Please prepare a new version of your paper by January 13 taking the reviewers' feedback into account. They offer great advice on how to make this an even stronger chapter.

**Comment by tzimmermsr** [comment]
Thanks for the revision @tomFr. The chapter is good to go from my side. 

I still recommend that you include something about Per's comment in the final version:
- [x] "Another issue that may be worth mentioning is the relation between multiple individual's productivity, i.e. the team or project level. It could benefit the team if one individual does something that lowers his/her individual productivity. The message is: don't sub optimize on the individual." (@pruneson46) 

Thanks,
Tom

**Comment by tomFr** [comment]
I integrated the comment from Per and added a sentence on the trade-off between individual and team productivity. Maybe you or Per could briefly check if it addresses the comment sufficiently.

**Comment by tzimmermsr** [comment]
Thanks @tomFr !
