### ISSUE TITLE
./turhanb/theGraph.md

### ISSUE THREAD

**Issue by timm** [ds4se/chapters#84]
After review, relabel to 'reviewTwo'. After second review, relabel to 'EditorsComment'.

**Comment by prechelt** [comment]
# Review template

Before filling in this review, please read our [Advice to Reviewers](how2review.md).

_(If you have confidential comments about this chapter, please email them to one of the book editors._)

## Title of chapter

Insights Trump Predictions!

## URL to the chapter

https://github.com/ds4se/chapters/blob/master/turhanb/theGraph.md#insights-trump-predictions

## Message?

Helpful analytics may be much simpler than the hardly-helpful ones you attempt

## Accessible?

Yes.
Would become still better after the following changes:
- leave out the "best" and "worst" lines from the plot
- explain the term "latent"
- include a short legend directly in the graph
- plot teams as squares, not circles
- simplify wording a bit in "How to act" section

## Size?

Length is fine.

What are the aspects of the chapter that authors  SHOULD  change?
- The summary at the end does not fit to the story told before:
  "Even though the accuracy of our predictor was perceived to be good, 
  coming up with a useful presentation of the predictions for practitioners 
  was the real challenge."
  This is not the point of your actual story.
  In the story, you analyzed a different (and much simpler-to-analyze!)
  aspect of the data in order to produce something useful.
  The success did not come from a better presentation, it came from
  asking a different (and much-simpler-to-answer) question.

## Gotta Mantra?

(Burak has a fine mantra already.)

## Best Points

What are the best points of the chapter that the authors should NOT change?

The core of the story is fine. Don't touch.
The storytelling is a tad complicated in the middle
and the summary does not yet fit, but overall this is going to be
a VERY nice chapter.

**Comment by taoxiease** [comment]
# Review template

## Title of chapter

Insights Trump Predictions!

## URL to the chapter

https://github.com/ds4se/chapters/blob/master/turhanb/theGraph.md

## Message?

After unsuccessful adoption of the initial software analytics tool focusing on predicting fault prone code sections, the authors developed a visualization of the issue reports.

## Accessible?

Good.

## Size?

The authors state "Though the project was a huge success in terms of scholarly outcomes and performance measures, we had run into difficulties in communicating the results to the practitioners." The authors are suggested to remove "huge" because different readers may have different expectations on how "huge" is "huge".

"with over 100.000 lines of code." Please replace "." with ",".

"They indicated that such performance figures were not useful to have an impact in their daily work, and pointing out error-prone sections within files was regarded as stating the obvious." The authors should give more elaboration on why "error-prone sections within files was regarded as stating the obvious". For example, what are these "error-prone sections" and how the practitioners already knew that these sections are error-prone without looking at the results of the analytics tool.

The wording of "error" shall be replaced. There are three related words in the testing literature: "fault", "error", and "failure", with distinct meanings. The authors shall dig out these meanings and pick the right wording.

## Gotta Mantra?

The existing title and advocated comparison of prediction vs. exploration (e.g., "insights") are not rigorous. Basically the authors tried their prediction approach but it didn't work in practice, and then the authors switched to focus on visualization of software project information, and it worked. Such observation doesn't lead to the conclusion "Insights Trump Predictions". This authors didn't provide insights on why their prediction work didn't work (simply saying that the results are expected is not insightful). The CRANE system (with some prediction features) was a successful tech adoption case. So it is not the case that there exists no single system/case where prediction works. 

## Best Points

The discussion on why the visualization work got adopted and provided value in practice.

**Comment by tzimmermsr** [comment]
@turhanb Please prepare a new version of your paper by January 13 taking the reviewers' feedback into account. The reviews offer great advice on how to make this an even stronger chapter.

I second Lutz's comment about the summary. 

I second Tao's comment that the title might not be a good fit. There are cases where prediction works; in your case the engineers were just looking for different insight than what prediction could provide. As Lutz said, your success came by asking a simpler question, that was more relevant to the team.

**Comment by turhanb** [comment]
thanks for the feedback! I've made necessary changes to address them (pls see [Revision.pdf](https://github.com/ds4se/chapters/files/101849/Revision.pdf) for how I handled them). Please note the title (and mantra) is updated.

**Comment by tzimmermsr** [comment]
Thanks @turhanb!
