### ISSUE TITLE
./zhang-xie/SoftwareAnalyticsInPractice.md

### ISSUE THREAD

**Issue by timm** [ds4se/chapters#90]
After review, relabel to 'reviewTwo'. After second review, relabel to 'EditorsComment'.

**Comment by tzimmermsr** [comment]
Review by @trevorcarnahan (copied from #100)

## Title of chapter

_Software Analytics in Practice_

## URL to the chapter

_https://github.com/ds4se/chapters/blob/master/zhang-xie/SoftwareAnalyticsInPractice.md_

## Message?

_Software Analytics can help eng. productivity, product quality, and user experience by producing actionable insights in practice._

## Accessible?

_Yes, the content was accessible to the generalist._

## Size?

_The chapter is a good length._

_I struggled a bit with the flow of the sections. I'm not sure why "Research Topic" is in the "in Practice" chapter, it stands out a bit.  Maybe if the title clarified this was from the researcher point of view it would be clearer._

_Consider less discussion of what Software Analytics is (since it is heavily covered by the rest of the chapters/book) and more content, with specific examples or story, on your experience putting it into practice with the business impact of it to set the hook._

## Gotta Mantra?

_Nothing is jumping to mind here… maybe something like:_
_Putting Software Analytics Research into Practice_
_Help my Software Analytics Research Resonate with Practice_

## Best Points

_I liked the last section on your experiences and "Evaluation criteria tied with real tasks…" (results) and the example it gave.  This was a good concrete example of connection to practice._

**Comment by tzimmermsr** [comment]
Review by @siravegas (copied from #113)

# Review template

Before filling in this review, please read our [Advice to Reviewers](how2review.md).

_(If you have confidential comments about this chapter, please email them to one of the book editors._)

## Title of chapter

_Software Analytics in Practice._

## URL to the chapter

_https://github.com/ds4se/chapters/blob/master/zhang-xie/SoftwareAnalyticsInPractice.md_

## Message?

What is the chapter's  clear and approachable take away message?

_The chapter describes what analytics involves in the software context as well as some experiences using it._

## Accessible?

Is the chapters written for a generalist audience (no excessive use of technical terminology) with a minimum of diagrams and references?
How can it be made more accessible to generalist?

_The paper is written for a generalist audience. It does not need to be made more accessible._

## Size?

Is the chapter the right length?

_Yes._

Should anything missing be added?

_An example at the beginning of the paper could make it more appealing._

Can anything superfluous be removed (e.g. by deleting some section that does not work so well or  by using less jargon, less formulae, lees diagrams, less references).?

_If the authors need more space when adding the example, the "research topic", "target audience" and "input" sections include information already mentioned at the beginning of the chapter._

What are the aspects of the chapter that authors  SHOULD  change?

_Already mentioned above._

## Gotta Mantra?

We encouraged (but did not require) the chapter title to be a mantra or something cute/catchy, i.e., some slogan reflecting best practice for data science for SE?  If you have suggestion for a better title, please put them here.

_The current title "Software Analytics in Practice" only reflects the contents of the last part of the chapter. According to the third paragraph of the chapter, it "discusses software analytics from six perspectives [...]. We also share our experiences on putting software analytics into practice"._

_Perhaps the title should reflect more accurately the contents of the chapter. When I started to read it, I expected something different from what I read. A possibility could be starting the title with something like "Data Analytics in the Software Domain", and then perhaps add something that helps understand better what the chapter is about (essential aspects to be taken into consideration or something like that)._

## Best Points

What are the best points of the chapter that the authors should NOT change?

_Definitely, the last section of the chapter (experiences on putting software analytics into practice) is the most useful one. It should not be changed at all._

**Comment by tzimmermsr** [comment]
@taoxiease @dongmeizhang Please take a look at the reviews and submit a new version by January 13. Both reviews offer great advice on how to make this a stronger chapter.

I recommend to drop the comparison with software intelligence and analytics for software development in the beginning since it does not add much (okay to keep your definition of software analytics in the introduction). Most readers won't get the nuances on how you perceive the difference between those three concepts. Personally, I feel that they are all the same concept and just the names are different (we had this discussion before). What I like about your papers is how you emphasized the trinity of data sources (research topics) and technology pillars. It's a recommendation, you make the final decision.

**Comment by taoxiease** [comment]
@tzimmermsr The revisions are done by @dongmeizhang and me to address review comments. Please double check. Thanks!
