### ISSUE TITLE
./rotella/AdvancesReleaseReadiness.md

### ISSUE THREAD

**Issue by trevorcarnahan** [ds4se/chapters#99]
## Title of chapter

_Advances in Release Readiness_
## URL to the chapter

_https://github.com/ds4se/chapters/blob/master/rotella/AdvancesReleaseReadiness.md_
## Message?

_There are strong correlations in defect incoming/fix rates to field reliably that can be exploited for predictive release execution and planning, and have been at Cisco._
## Accessible?

_I enjoyed reading the chapter and appreciated the applied nature of the results._

_I'd go ahead and try to incorporate reliable into the chapter title to set more context for the reader going in._

_An example chart in the Predictive Test Metrics section to summarize a release in "good shape" or "in trouble" could help the reader comprehend the actual rates, asymptote/GOS, 80% target, quickly._

_For the URC - I liked the limit enumeration. One curiosity it left me with was if it covered v1 products. My assumption is results were from mature systems at Cisco._

_Goel-Okumoto Shaped (GOS) and NHPP concepts should be footnoted for the readers to learn more about them._
## Size?

_The chapter is a good length. There are a lot of good material packed in there._
## Gotta Mantra?

_Ready for reliable release_
_We predict a reliable release!_
_Improving reliability, one release at a time_
## Best Points

_I liked the treatment of BET, and making it more useful/actionable to the teams and leading towards NRT value (driving behavior) towards a reliability goal.  Business impact speaks.  And as a fellow practitioner, I also appreciated the summary_

**Comment by pgbovine** [comment]
## Title of chapter

Advances in Release Readiness

## URL to the chapter

https://github.com/ds4se/chapters/blob/master/rotella/AdvancesReleaseReadiness.md

## Message?

What is the chapter's  clear and approachable take away message?

Developing simple yet effective metrics for release readiness is important for a software organization.

## Accessible?

This chapter feels a bit too technical and number-heavy for a generalist audience. It reads almost like a research paper draft or technical whitepaper. Perhaps one way to make it appeal to a practitioner audience is to think about this chapter as "talking directly to a data scientist." If the authors were talking directly to a data scientist, how would they present this same information? I don't have any concrete ideas here since this isn't my area of speciality. But maybe one starting point is to have an actionable take-away message. In other words, as a data scientist, how can my daily workflow improve after reading this chapter? Right now I've learned a bit about what you do at Cisco, but if I don't have the same development environment in my organization, what general lessons can I still take away from this chapter?

## Size?

Length seems fine. In fact, I would suggest to add some charts or graphs since there are a lot of numbers presented throughout the chapter.

## Gotta Mantra?

Perhaps summarize your main finding in the title? e.g., "Metrics X and Y are crucial for improving release readiness"

## Best Points

The introductory section was good, so don't change it much.

**Comment by tzimmermsr** [comment]
Great experience report Pete. Very impressive work. I like it. Please take a look at the reviews and submit a new version of the chapter by January 13.

Specifically, please focus on making the chapter slightly less technical. Right now your chapter is requires somewhere between Data Science 201 and 301. Can you increase the take away for people who just started with Data Science 101 and don't know all the details of the modeling techniques. Some charts or graphs might be a good way to help the reader understand the concepts.

Feel free to add a few references to your relevant papers, in case the reader wants to learn more.
